# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D9Transfer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='transfer_d9_block_n_a192a7_idx'), models.Index(fields=['timestamp'], name='transfer_d9_timesta_a7cab3_idx'), models.Index(fields=['extrinsic_hash'], name='transfer_d9_extrins_c5ac4a_idx'), models.Index(fields=['contract'], name='transfer_d9_contrac_2b0a7f_idx'), models.Index(fields=['contract_address'], name='transfer_d9_contrac_4b011e_idx'), models.Index(fields=['kind'], name='transfer_d9_kind_7a6e0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='USDTTransfer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='transfer_us_block_n_99ac45_idx'), models.Index(fields=['timestamp'], name='transfer_us_timesta_a3e07f_idx'), models.Index(fields=['extrinsic_hash'], name='transfer_us_extrins_1a66ff_idx'), models.Index(fields=['contract'], name='transfer_us_contrac_e52dd5_idx'), models.Index(fields=['contract_address'], name='transfer_us_contrac_d340e4_idx'), models.Index(fields=['kind'], name='transfer_us_kind_2fd953_idx')],
            },
        ),
    ]
