# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidity',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='liquidity_l_block_n_0971d2_idx'), models.Index(fields=['timestamp'], name='liquidity_l_timesta_8171cc_idx'), models.Index(fields=['extrinsic_hash'], name='liquidity_l_extrins_64dfab_idx'), models.Index(fields=['contract'], name='liquidity_l_contrac_7ea093_idx'), models.Index(fields=['contract_address'], name='liquidity_l_contrac_8b45d8_idx'), models.Index(fields=['kind'], name='liquidity_l_kind_9ff235_idx')],
            },
        ),
    ]
