# Generated by Django 5.0.6 on 2024-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVoting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='node_addvot_block_n_abd37a_idx'), models.Index(fields=['timestamp'], name='node_addvot_timesta_667b16_idx'), models.Index(fields=['extrinsic_hash'], name='node_addvot_extrins_109c8d_idx'), models.Index(fields=['contract'], name='node_addvot_contrac_756619_idx'), models.Index(fields=['contract_address'], name='node_addvot_contrac_233c33_idx'), models.Index(fields=['kind'], name='node_addvot_kind_714aa6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeReward',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='node_nodere_block_n_9e8f44_idx'), models.Index(fields=['timestamp'], name='node_nodere_timesta_15232a_idx'), models.Index(fields=['extrinsic_hash'], name='node_nodere_extrins_d12eab_idx'), models.Index(fields=['contract'], name='node_nodere_contrac_d8d7a2_idx'), models.Index(fields=['contract_address'], name='node_nodere_contrac_c5b9eb_idx'), models.Index(fields=['kind'], name='node_nodere_kind_b967a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeWithdraw',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='node_nodewi_block_n_c56d6e_idx'), models.Index(fields=['timestamp'], name='node_nodewi_timesta_c03a6a_idx'), models.Index(fields=['extrinsic_hash'], name='node_nodewi_extrins_df799c_idx'), models.Index(fields=['contract'], name='node_nodewi_contrac_eb9243_idx'), models.Index(fields=['contract_address'], name='node_nodewi_contrac_7cf0c8_idx'), models.Index(fields=['kind'], name='node_nodewi_kind_154edd_idx')],
            },
        ),
    ]
