# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiveGreenPoints',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='merchant_gi_block_n_0139a7_idx'), models.Index(fields=['timestamp'], name='merchant_gi_timesta_b8b27d_idx'), models.Index(fields=['extrinsic_hash'], name='merchant_gi_extrins_9c5623_idx'), models.Index(fields=['contract'], name='merchant_gi_contrac_64cfcb_idx'), models.Index(fields=['contract_address'], name='merchant_gi_contrac_f4f013_idx'), models.Index(fields=['kind'], name='merchant_gi_kind_6f585f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='merchant_pa_block_n_b51d84_idx'), models.Index(fields=['timestamp'], name='merchant_pa_timesta_2737f4_idx'), models.Index(fields=['extrinsic_hash'], name='merchant_pa_extrins_9d3d1c_idx'), models.Index(fields=['contract'], name='merchant_pa_contrac_8ca6b4_idx'), models.Index(fields=['contract_address'], name='merchant_pa_contrac_28701b_idx'), models.Index(fields=['kind'], name='merchant_pa_kind_241848_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='merchant_su_block_n_50979d_idx'), models.Index(fields=['timestamp'], name='merchant_su_timesta_bb2fcd_idx'), models.Index(fields=['extrinsic_hash'], name='merchant_su_extrins_08c2d5_idx'), models.Index(fields=['contract'], name='merchant_su_contrac_4f2159_idx'), models.Index(fields=['contract_address'], name='merchant_su_contrac_7f8157_idx'), models.Index(fields=['kind'], name='merchant_su_kind_394f3f_idx')],
            },
        ),
    ]
