# Generated by Django 5.0.6 on 2024-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burning',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='withdraw_bu_block_n_d64f62_idx'), models.Index(fields=['timestamp'], name='withdraw_bu_timesta_40d7c1_idx'), models.Index(fields=['extrinsic_hash'], name='withdraw_bu_extrins_e7437a_idx'), models.Index(fields=['contract'], name='withdraw_bu_contrac_cbd3f9_idx'), models.Index(fields=['contract_address'], name='withdraw_bu_contrac_63ad08_idx'), models.Index(fields=['kind'], name='withdraw_bu_kind_7db01d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='withdraw_me_block_n_0abdd9_idx'), models.Index(fields=['timestamp'], name='withdraw_me_timesta_ff1621_idx'), models.Index(fields=['extrinsic_hash'], name='withdraw_me_extrins_30f989_idx'), models.Index(fields=['contract'], name='withdraw_me_contrac_02ebcf_idx'), models.Index(fields=['contract_address'], name='withdraw_me_contrac_1f0049_idx'), models.Index(fields=['kind'], name='withdraw_me_kind_e960c8_idx')],
            },
        ),
    ]
