# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='cross_chain_block_n_d2380d_idx'), models.Index(fields=['timestamp'], name='cross_chain_timesta_26e46e_idx'), models.Index(fields=['extrinsic_hash'], name='cross_chain_extrins_cad59d_idx'), models.Index(fields=['contract'], name='cross_chain_contrac_97d19a_idx'), models.Index(fields=['contract_address'], name='cross_chain_contrac_3abb57_idx'), models.Index(fields=['kind'], name='cross_chain_kind_4dc867_idx')],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='cross_chain_block_n_981703_idx'), models.Index(fields=['timestamp'], name='cross_chain_timesta_66b134_idx'), models.Index(fields=['extrinsic_hash'], name='cross_chain_extrins_3d348d_idx'), models.Index(fields=['contract'], name='cross_chain_contrac_eafdc7_idx'), models.Index(fields=['contract_address'], name='cross_chain_contrac_e128e2_idx'), models.Index(fields=['kind'], name='cross_chain_kind_cd9f94_idx')],
            },
        ),
    ]
