# Generated by Django 5.0.6 on 2024-07-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.CharField(max_length=255)),
                ('block_hash', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('extrinsic_hash', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('contract', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('data', models.JSONField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['block_number'], name='market_make_block_n_aafcdd_idx'), models.Index(fields=['timestamp'], name='market_make_timesta_7e91a6_idx'), models.Index(fields=['extrinsic_hash'], name='market_make_extrins_edf6fb_idx'), models.Index(fields=['contract'], name='market_make_contrac_2d15ae_idx'), models.Index(fields=['contract_address'], name='market_make_contrac_882339_idx'), models.Index(fields=['kind'], name='market_make_kind_f6c700_idx')],
            },
        ),
    ]
